#!/bin/bash
# AUT0Script for Amnesty International - Mobile Verification Toolkit on (macOS)
# Check your Privatcy Settings -> Disc Access for Terminal.
# Run this via oneClick from Finder or from commandline ./mvta
# FILE NAME	= mvta
# AUTHOR	= n33dful.l4bs
# VERSION	= 1.01m

# Variables
WorkDirectory="/Users/`whoami`"
SourceBackup=`ls $WorkDirectory/Library/Application\ Support/MobileSync/Backup`
Stix2File="$WorkDirectory/mvt/investigations/2021-07-18_nso/pegasus.stix2"

# If nothing exist!?
[ ! -d $WorkDirectory/mvt ] && mkdir -p $WorkDirectory/mvt/{DecryptedBackup,CheckedBackup}
[ ! -f $Stix2File ] && git clone https://github.com/AmnestyTech/investigations/ $WorkDirectory/mvt/investigations
clear

# List found Backups
PS3="Select UUID by number :         "
select UUID in $SourceBackup; do

	# Enter Backup-Password for decryption
	printf "\e[0;32mType Backup-Password            "
	read -s BAKPW0
	printf "[ \e[0;36mPASS\e[0;32m ]\nRetype Backup-Password          "
	read -s BAKPW1

	# Check entered Passwords for match.
	if [ $BAKPW0 = $BAKPW1 ]; then

		# Entered Passwords are equality
		printf "[ \e[0;36mPASS\e[0;32m ]\n"

		# Decrypting the Backup
		printf "\e[0;32mDecrypting in progress...       "
		mvt-ios decrypt-backup -p $BAKPW0 -d $WorkDirectory/mvt/DecryptedBackup $WorkDirectory/Library/Application\ Support/MobileSync/Backup/$UUID >>$WorkDirectory/mvt/Decrypt.log
		printf "[ \e[0;36mDONE\e[0;32m ]\n"

		# Check the decrypted Backup.
		printf "\e[0;32mChecking in progress...         "
		mvt-ios check-backup -i $Stix2File -o $WorkDirectory/mvt/CheckedBackup $WorkDirectory/mvt/DecryptedBackup >>$WorkDirectory/mvt/Check.log

		# Show resultats.
		if [ -f $WorkDirectory/mvt/CheckedBackup/*detected* ]; then

			# If Backup detected!
			printf "[\e[0;31mDETECT\e[0;32m]\n"
			open /System/Library/CoreServices/Finder.app $WorkDirectory/mvt/CheckedBackup
		else
				
			# If Backup Clean.
			printf "[\e[0;36m GOOD \e[0,32m]\n"
			[ -d $WorkDirectory/mvt/CheckedBackup ] && rm -R $WorkDirectory/mvt/CheckedBackup/*
		fi

		# Delete last Session :)
		printf "\e[0;32mDelete last Session...          "
		[ -d $WorkDirectory/mvt/DecryptedBackup ] && rm -R $WorkDirectory/mvt/DecryptedBackup/*
		printf "[ \e[0;36mDONE\e[0;32m ]\n"
		break;
	else

		# Entered Passwords are mismatched
		printf "[ \e[0;31mFAIL\e[0;32m ]\n\n"
		break;
	fi
	break;
done