#!/bin/bash
# AUT0Script for Amnesty International - Mobile Verification Toolkit on (macOS)
# Check your Privatcy Settings -> Disc Access for Terminal.
# Run this via oneClick from Finder or from commandline ./mvta
# FILE NAME	= mvta
# AUTHOR	= n33dful-l4bs :)
# VERSION	= 1.05m

# Variables
WorkDirectory="/Users/`whoami`"
SourceBackup=`ls $WorkDirectory/Library/Application\ Support/MobileSync/Backup`
Stix2FileLocation=`ls $WorkDirectory/Library/Application\ Support/mvt/indicators`

# If nothing exist!?
[ ! -d $WorkDirectory/mvt ] && mkdir -p $WorkDirectory/mvt/{DecryptedBackup,CheckedBackup}
clear

# Update IOCS Files
printf "\e[0;32mUpdate IOCS...                  "
mvt-ios download-iocs >> $WorkDirectory/mvt/Session.log
printf "[ \e[0;36mDONE\e[0;32m ]\n"

# List found Backups
PS3="Select UUID by number :         "
select UUID in $SourceBackup; do

	# Enter Backup-Password for decryption
	printf "\e[0;32mType Backup-Password            "
	read -s BAKPW0
	printf "[ \e[0;36mPASS\e[0;32m ]\nRetype Backup-Password          "
	read -s BAKPW1

	# Check entered Passwords for match.
	if [ $BAKPW0 = $BAKPW1 ]; then

		# Entered Passwords are equality
		printf "[ \e[0;36mPASS\e[0;32m ]\n"

		# Decrypting the Backup
		printf "\e[0;32mDecrypting in progress...       "
		mvt-ios decrypt-backup -p $BAKPW0 -d $WorkDirectory/mvt/DecryptedBackup $WorkDirectory/Library/Application\ Support/MobileSync/Backup/$UUID >>$WorkDirectory/mvt/Session.log
		printf "[ \e[0;36mDONE\e[0;32m ]\n"

		# Select Stix2 File
		PS3="Select Stix2 File by Number :  "
		select IOCS in $Stix2FileLocation; do

			# Check the decrypted Backup.
			printf "\e[0;32mChecking in progress...         "
			mvt-ios check-backup -i $WorkDirectory/Library/Application\ Support/mvt/indicators/$IOCS -o $WorkDirectory/mvt/CheckedBackup $WorkDirectory/mvt/DecryptedBackup >>$WorkDirectory/mvt/Session.log
			
			# Show resultats.
			if [ -f $WorkDirectory/mvt/CheckedBackup/*detected* ]; then

				# If Backup detected!
				printf "[\e[0;31mDETECT\e[0;32m]\n"
				open /System/Library/CoreServices/Finder.app $WorkDirectory/mvt/CheckedBackup
			else
				
				# If Backup Clean.
				printf "[\e[0;36m GOOD \e[0,32m]\n"
				[ -d $WorkDirectory/mvt/CheckedBackup ] && rm -R $WorkDirectory/mvt/CheckedBackup/*
			fi
			break;
		done

		# Delete last Session :)
		printf "\e[0;32mDelete last Session...          "
		[ -d $WorkDirectory/mvt/DecryptedBackup ] && rm -R $WorkDirectory/mvt/DecryptedBackup/*
		mv $WorkDirectory/mvt/Session.log $WorkDirectory/mvt/$UUID.log
		printf "[ \e[0;36mDONE\e[0;32m ]\n"
		break;
	else

		# Entered Passwords are mismatched
		printf "[ \e[0;31mFAIL\e[0;32m ]\n\n"
		break;
	fi
	break;
done